<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find fishbot_description)/urdf/fishbot/common_inertia.xacro" />
    
    <xacro:macro name="base_xacro" params="length radius">

        <link name="base_footprint" />
        <!-- 可以理解为机器人在地上的投影，x，y是一样的，z是从base_link到地面的距离 -->

        <joint name="base_joint" type="fixed">
            <parent link="base_footprint" />
            <child link="base_link" />
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0 0 0" />
            <!-- -0.001是为了让他紧贴地面 -->
        </joint>

        <link name="base_link">
        <!-- 部件的外观描述 -->
            <visual>
                <!-- 沿着自己几何中心的偏移和旋转量 -->
                <origin xyz="0 0 0.0" rpy="0 0 0" />

                <!-- 几何形状 -->
                <geometry>
                    <cylinder length="${length}" radius="${radius}" />
                </geometry>

                <!-- 材质颜色 -->
                <material name="blue">
                    <color rgba="0.1 0.1 1.0 0.5"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 0.0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${length}" radius="${radius}" />
                </geometry>
                <material name="blue">
                    <color rgba="0.1 0.1 1.0 0.5"/>
                </material>
            </collision>

            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>
        </link>
    </xacro:macro>
</robot>